pub mod requests;
use chrono::{DateTime, Local, TimeZone};
use std::env;
use std::fs;
use std::path::Path;
use std::process;
use std::thread;
use std::time::Duration;
use walkdir::WalkDir;

/*
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nunc id cursus metus aliquam eleifend mi in nulla. Placerat duis ultricies lacus sed. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Dignissim suspendisse in est ante in. Id semper risus in hendrerit gravida rutrum quisque. Donec ac odio tempor orci. Lobortis mattis aliquam faucibus purus in massa tempor. Facilisis leo vel fringilla est ullamcorper.

Enim sit amet venenatis urna cursus eget nunc. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Ut venenatis tellus in metus vulputate eu. Ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Velit ut tortor pretium viverra. Ipsum a arcu cursus vitae congue mauris rhoncus aenean. Sapien faucibus et molestie ac feugiat sed lectus. Fringilla ut morbi tincidunt augue interdum velit. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Eu sem integer vitae justo. Sapien nec sagittis aliquam malesuada. Et malesuada fames ac turpis egestas integer eget aliquet. Bibendum enim facilisis gravida neque convallis a. Odio eu feugiat pretium nibh ipsum consequat nisl. Quam elementum pulvinar etiam non quam lacus suspendisse.

Viverra nibh cras pulvinar mattis nunc. Sagittis id consectetur purus ut faucibus. Arcu dictum varius duis at consectetur lorem donec massa. Ut tortor pretium viverra suspendisse potenti. Lacus laoreet non curabitur gravida arcu ac tortor. Fames ac turpis egestas maecenas. Accumsan sit amet nulla facilisi morbi tempus iaculis. Nunc congue nisi vitae suscipit. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Vitae purus faucibus ornare suspendisse sed nisi lacus. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Risus commodo viverra maecenas accumsan lacus.

At volutpat diam ut venenatis tellus in. Quis lectus nulla at volutpat diam. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Est ultricies integer quis auctor elit. Nulla porttitor massa id neque aliquam vestibulum morbi. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Aliquam ultrices sagittis orci a scelerisque. In egestas erat imperdiet sed euismod nisi. Lacus sed turpis tincidunt id aliquet risus feugiat. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Purus semper eget duis at tellus at urna. Volutpat est velit egestas dui id ornare. Orci ac auctor augue mauris augue. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id.

Dolor morbi non arcu risus quis. In est ante in nibh mauris cursus mattis molestie. Est placerat in egestas erat imperdiet. Fermentum et sollicitudin ac orci phasellus egestas tellus. At in tellus integer feugiat scelerisque varius. Nunc congue nisi vitae suscipit tellus mauris a diam. Lectus quam id leo in vitae turpis massa. Malesuada fames ac turpis egestas integer eget aliquet nibh. Facilisis sed odio morbi quis. Et netus et malesuada fames ac turpis. Tortor posuere ac ut consequat semper viverra nam. Ultricies mi eget mauris pharetra et ultrices neque ornare. Commodo odio aenean sed adipiscing diam. Morbi leo urna molestie at elementum eu facilisis. Mattis rhoncus urna neque viverra justo nec ultrices dui.

Leo in vitae turpis massa sed elementum tempus egestas sed. In egestas erat imperdiet sed euismod. Morbi blandit cursus risus at ultrices. Felis eget velit aliquet sagittis id consectetur. Varius morbi enim nunc faucibus a pellentesque. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Malesuada fames ac turpis egestas integer eget aliquet nibh. In arcu cursus euismod quis viverra nibh cras pulvinar. Dignissim cras tincidunt lobortis feugiat. Rutrum quisque non tellus orci ac auctor augue mauris augue. Quis auctor elit sed vulputate mi sit.

Amet aliquam id diam maecenas ultricies mi eget mauris pharetra. Est ultricies integer quis auctor elit sed vulputate. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Integer eget aliquet nibh praesent tristique magna sit amet purus. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Aliquet bibendum enim facilisis gravida neque convallis. Nunc mattis enim ut tellus elementum sagittis vitae. Sapien et ligula ullamcorper malesuada. Facilisi morbi tempus iaculis urna id volutpat lacus. Nascetur ridiculus mus mauris vitae. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Elementum nibh tellus molestie nunc non blandit massa enim nec. Cras adipiscing enim eu turpis egestas pretium. Pretium nibh ipsum consequat nisl. Neque vitae tempus quam pellentesque nec nam aliquam sem et.

Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Rutrum quisque non tellus orci ac auctor augue mauris. Nunc mattis enim ut tellus elementum sagittis vitae. Fringilla urna porttitor rhoncus dolor purus. Nisi est sit amet facilisis magna etiam. Sit amet massa vitae tortor condimentum. Adipiscing vitae proin sagittis nisl rhoncus mattis. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Mi sit amet mauris commodo quis imperdiet massa. Sagittis vitae et leo duis ut diam quam. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Diam maecenas sed enim ut. Dictum at tempor commodo ullamcorper a lacus vestibulum sed. Tincidunt dui ut ornare lectus sit. A lacus vestibulum sed arcu non. Lobortis feugiat vivamus at augue. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit.

Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Dolor magna eget est lorem ipsum dolor sit amet consectetur. Dolor sit amet consectetur adipiscing elit. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Tortor at auctor urna nunc id cursus metus aliquam. In massa tempor nec feugiat nisl pretium fusce. Enim tortor at auctor urna. Scelerisque viverra mauris in aliquam sem fringilla ut morbi tincidunt. Quis hendrerit dolor magna eget est. Tempus urna et pharetra pharetra massa massa ultricies mi. Sit amet nisl suscipit adipiscing bibendum.

Blandit massa enim nec dui nunc. Nisl purus in mollis nunc sed id semper risus. Morbi tristique senectus et netus et malesuada fames ac. Pulvinar mattis nunc sed blandit. Duis convallis convallis tellus id interdum velit laoreet id. Risus feugiat in ante metus dictum at. Dolor purus non enim praesent elementum facilisis leo. Auctor urna nunc id cursus metus aliquam eleifend mi. Habitant morbi tristique senectus et. Id volutpat lacus laoreet non curabitur.

Nisl vel pretium lectus quam id leo in. Dolor sit amet consectetur adipiscing elit. Euismod lacinia at quis risus. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Quisque id diam vel quam elementum pulvinar etiam non. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Cursus metus aliquam eleifend mi in nulla posuere. Luctus accumsan tortor posuere ac ut consequat semper viverra. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Mauris vitae ultricies leo integer. Tempus urna et pharetra pharetra. Pretium lectus quam id leo in vitae turpis massa sed. Sapien nec sagittis aliquam malesuada. Semper risus in hendrerit gravida rutrum quisque non. Lacus suspendisse faucibus interdum posuere. Lorem ipsum dolor sit amet consectetur adipiscing. Ut porttitor leo a diam. Lorem dolor sed viverra ipsum. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed.

Nunc sed blandit libero volutpat sed cras. Viverra orci sagittis eu volutpat odio. In pellentesque massa placerat duis ultricies. Bibendum neque egestas congue quisque egestas diam. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Cursus turpis massa tincidunt dui ut ornare. Malesuada nunc vel risus commodo viverra. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Purus gravida quis blandit turpis cursus in hac. Gravida cum sociis natoque penatibus. Fermentum iaculis eu non diam phasellus vestibulum. Pellentesque habitant morbi tristique senectus et netus et malesuada. Vitae purus faucibus ornare suspendisse sed. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere.

Arcu cursus euismod quis viverra. Mauris nunc congue nisi vitae suscipit. Rhoncus dolor purus non enim praesent elementum. Vitae congue eu consequat ac felis. Ultricies mi quis hendrerit dolor magna eget. Dictumst quisque sagittis purus sit amet volutpat consequat. Porttitor rhoncus dolor purus non enim praesent elementum facilisis leo. Justo laoreet sit amet cursus sit amet dictum sit. Vitae congue eu consequat ac felis donec et odio. Amet aliquam id diam maecenas. Gravida dictum fusce ut placerat. Nam at lectus urna duis convallis convallis tellus id.

Facilisis leo vel fringilla est ullamcorper eget. Neque aliquam vestibulum morbi blandit cursus. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Cursus in hac habitasse platea dictumst. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Urna duis convallis convallis tellus id. Pretium nibh ipsum consequat nisl. Et malesuada fames ac turpis egestas maecenas pharetra convallis. Cursus metus aliquam eleifend mi in nulla. Fames ac turpis egestas maecenas pharetra. At consectetur lorem donec massa sapien faucibus et molestie. Et leo duis ut diam quam nulla. Sed adipiscing diam donec adipiscing tristique risus nec. Nisi scelerisque eu ultrices vitae. Non tellus orci ac auctor augue. Imperdiet nulla malesuada pellentesque elit eget. Vitae semper quis lectus nulla at volutpat diam ut. Elit ullamcorper dignissim cras tincidunt lobortis. Habitant morbi tristique senectus et netus et.

Egestas diam in arcu cursus euismod quis viverra nibh cras. Facilisis mauris sit amet massa vitae tortor condimentum. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Sit amet cursus sit amet dictum. Massa tincidunt dui ut ornare lectus sit. Magna fermentum iaculis eu non diam phasellus vestibulum lorem. Enim diam vulputate ut pharetra sit amet aliquam. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Lectus magna fringilla urna porttitor. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus.

Morbi quis commodo odio aenean. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Sagittis vitae et leo duis ut diam quam nulla porttitor. Lorem ipsum dolor sit amet. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Ut pharetra sit amet aliquam id diam. Elit eget gravida cum sociis natoque penatibus et. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Morbi quis commodo odio aenean sed. Vitae elementum curabitur vitae nunc sed velit. Vel orci porta non pulvinar. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Auctor eu augue ut lectus arcu bibendum at varius vel.

Leo a diam sollicitudin tempor id eu. Lacus vel facilisis volutpat est. Mauris sit amet massa vitae tortor condimentum lacinia quis. Facilisis mauris sit amet massa vitae tortor. Molestie nunc non blandit massa enim nec. Dui id ornare arcu odio ut sem. Aliquet enim tortor at auctor urna nunc id cursus. Sagittis id consectetur purus ut faucibus pulvinar elementum. Praesent elementum facilisis leo vel fringilla. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Pharetra vel turpis nunc eget. Integer feugiat scelerisque varius morbi enim. Donec ultrices tincidunt arcu non sodales neque sodales ut.

Donec pretium vulputate sapien nec sagittis. Commodo viverra maecenas accumsan lacus vel facilisis. Adipiscing vitae proin sagittis nisl rhoncus mattis. Eget magna fermentum iaculis eu non diam. Volutpat est velit egestas dui id ornare arcu odio ut. Lorem donec massa sapien faucibus et. Interdum velit laoreet id donec ultrices tincidunt. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Pretium nibh ipsum consequat nisl vel pretium lectus. Feugiat in ante metus dictum at tempor commodo. Sem et tortor consequat id porta. Dui id ornare arcu odio ut sem nulla pharetra diam. Risus quis varius quam quisque id diam vel. Elementum curabitur vitae nunc sed velit dignissim. Sit amet purus gravida quis. Tellus elementum sagittis vitae et leo duis ut. Amet nisl suscipit adipiscing bibendum est ultricies. Eget sit amet tellus cras adipiscing enim eu turpis. Ultrices in iaculis nunc sed augue lacus viverra vitae. Nec ullamcorper sit amet risus nullam eget felis.

Porta non pulvinar neque laoreet suspendisse. Sed elementum tempus egestas sed. Sed vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Sociis natoque penatibus et magnis dis parturient montes nascetur. Feugiat in ante metus dictum. Nunc aliquet bibendum enim facilisis gravida neque convallis. Nec ullamcorper sit amet risus. Convallis aenean et tortor at risus. Neque volutpat ac tincidunt vitae. Lacus vestibulum sed arcu non odio euismod lacinia at quis.

Purus gravida quis blandit turpis cursus in. Faucibus turpis in eu mi bibendum neque egestas. Magna fringilla urna porttitor rhoncus dolor purus. Orci eu lobortis elementum nibh tellus molestie. Pulvinar neque laoreet suspendisse interdum consectetur. Volutpat est velit egestas dui id ornare arcu odio ut. Sed egestas egestas fringilla phasellus faucibus scelerisque. Id diam maecenas ultricies mi eget. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Dolor sit amet consectetur adipiscing elit. Quis commodo odio aenean sed.

Magna eget est lorem ipsum dolor. Blandit libero volutpat sed cras ornare arcu dui vivamus arcu. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Duis tristique sollicitudin nibh sit amet commodo. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Cras ornare arcu dui vivamus arcu felis. Turpis massa sed elementum tempus egestas sed. Sit amet massa vitae tortor condimentum. Congue nisi vitae suscipit tellus mauris a. Luctus accumsan tortor posuere ac ut consequat semper viverra. Tincidunt praesent semper feugiat nibh sed pulvinar. Justo donec enim diam vulputate ut pharetra. Blandit aliquam etiam erat velit scelerisque in.

Tellus in metus vulputate eu scelerisque felis imperdiet. Integer malesuada nunc vel risus commodo. Auctor neque vitae tempus quam. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Vitae congue mauris rhoncus aenean vel elit. Mi quis hendrerit dolor magna eget est lorem. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Magna ac placerat vestibulum lectus mauris. Erat pellentesque adipiscing commodo elit at. Gravida quis blandit turpis cursus in hac. Felis eget velit aliquet sagittis id consectetur purus ut. Diam donec adipiscing tristique risus nec. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Sed pulvinar proin gravida hendrerit. Volutpat ac tincidunt vitae semper quis lectus nulla at. Orci dapibus ultrices in iaculis nunc sed augue lacus. In nisl nisi scelerisque eu ultrices vitae. Pellentesque sit amet porttitor eget dolor morbi non. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Sit amet nisl purus in mollis nunc sed.

Facilisis magna etiam tempor orci eu lobortis elementum. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Morbi tristique senectus et netus et malesuada fames ac. Sociis natoque penatibus et magnis dis parturient montes. Libero justo laoreet sit amet. Amet consectetur adipiscing elit ut. Vitae justo eget magna fermentum iaculis. Mattis vulputate enim nulla aliquet porttitor. Viverra justo nec ultrices dui. Pellentesque pulvinar pellentesque habitant morbi tristique senectus. Urna cursus eget nunc scelerisque viverra mauris in aliquam. Feugiat scelerisque varius morbi enim nunc faucibus a. Et malesuada fames ac turpis. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Sit amet porttitor eget dolor morbi non arcu. Massa sed elementum tempus egestas. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. In pellentesque massa placerat duis ultricies lacus.

Pellentesque diam volutpat commodo sed. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Quis auctor elit sed vulputate mi sit amet mauris commodo. Vitae auctor eu augue ut lectus arcu. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Id semper risus in hendrerit gravida. Viverra nam libero justo laoreet sit amet. Fermentum dui faucibus in ornare quam viverra orci. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Tincidunt eget nullam non nisi est sit amet. Dignissim suspendisse in est ante in nibh mauris cursus. Eget magna fermentum iaculis eu. Quam lacus suspendisse faucibus interdum posuere lorem. At lectus urna duis convallis convallis tellus id interdum velit. Accumsan in nisl nisi scelerisque eu ultrices. Felis bibendum ut tristique et. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium.

Tortor condimentum lacinia quis vel eros donec ac. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Ac tortor dignissim convallis aenean et. Egestas pretium aenean pharetra magna. Elit ut aliquam purus sit amet. Urna cursus eget nunc scelerisque viverra mauris. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Enim diam vulputate ut pharetra sit. Tortor dignissim convallis aenean et. Dolor magna eget est lorem ipsum dolor sit. Sit amet purus gravida quis blandit. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Blandit libero volutpat sed cras ornare arcu dui. Ac tincidunt vitae semper quis.

At in tellus integer feugiat scelerisque varius morbi enim nunc. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec. Pharetra massa massa ultricies mi quis hendrerit dolor. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Pretium fusce id velit ut tortor pretium viverra suspendisse. In vitae turpis massa sed. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Vitae aliquet nec ullamcorper sit. Eget mi proin sed libero enim sed faucibus turpis in. Vitae semper quis lectus nulla at volutpat. Amet commodo nulla facilisi nullam vehicula. Viverra nam libero justo laoreet sit amet cursus sit. A pellentesque sit amet porttitor eget dolor morbi. Libero justo laoreet sit amet cursus sit amet dictum sit. Purus semper eget duis at. Nibh cras pulvinar mattis nunc sed blandit libero volutpat.

Volutpat blandit aliquam etiam erat velit scelerisque in dictum. Dui vivamus arcu felis bibendum ut tristique et egestas. Elementum eu facilisis sed odio. Erat velit scelerisque in dictum non consectetur a erat nam. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Lacinia quis vel eros donec ac. Eu sem integer vitae justo. Duis at consectetur lorem donec massa sapien faucibus et. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Enim facilisis gravida neque convallis a. Lorem ipsum dolor sit amet. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Pellentesque habitant morbi tristique senectus et netus et.

Et malesuada fames ac turpis egestas integer eget aliquet. Suscipit tellus mauris a diam maecenas sed enim. Volutpat odio facilisis mauris sit. Ante in nibh mauris cursus mattis molestie a iaculis at. Nibh tellus molestie nunc non blandit. Consectetur adipiscing elit duis tristique sollicitudin nibh. Morbi quis commodo odio aenean sed adipiscing. Nunc sed velit dignissim sodales ut eu sem integer vitae. In cursus turpis massa tincidunt dui ut. Nam aliquam sem et tortor consequat id. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Commodo elit at imperdiet dui accumsan sit amet nulla. Curabitur gravida arcu ac tortor dignissim convallis aenean et tortor. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Risus quis varius quam quisque. Pellentesque habitant morbi tristique senectus et netus et malesuada. Aliquam purus sit amet luctus. Nisl condimentum id venenatis a condimentum vitae sapien.

Sapien faucibus et molestie ac. Sit amet consectetur adipiscing elit duis. Nullam non nisi est sit amet. In egestas erat imperdiet sed euismod nisi porta. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Tortor condimentum lacinia quis vel eros donec ac odio. Magna fermentum iaculis eu non diam phasellus vestibulum. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Est ultricies integer quis auctor. Fermentum iaculis eu non diam phasellus vestibulum lorem sed risus. Viverra justo nec ultrices dui sapien eget. Metus vulputate eu scelerisque felis. Lacus sed turpis tincidunt id aliquet risus. Nibh praesent tristique magna sit amet purus gravida quis. Congue nisi vitae suscipit tellus. Sit amet facilisis magna etiam tempor.

Auctor eu augue ut lectus arcu bibendum. Pellentesque sit amet porttitor eget dolor. Viverra adipiscing at in tellus integer feugiat scelerisque varius. Lectus magna fringilla urna porttitor rhoncus dolor purus. In massa tempor nec feugiat. Cursus in hac habitasse platea dictumst quisque. Id leo in vitae turpis massa sed elementum tempus egestas. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Tortor at auctor urna nunc id cursus metus aliquam eleifend. Turpis in eu mi bibendum neque egestas congue quisque. Turpis massa tincidunt dui ut ornare lectus sit amet est. Hendrerit dolor magna eget est lorem. Amet risus nullam eget felis. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Tristique senectus et netus et malesuada. Urna condimentum mattis pellentesque id. Sociis natoque penatibus et magnis dis parturient montes nascetur.

Rutrum quisque non tellus orci ac auctor augue. Consequat semper viverra nam libero justo laoreet sit amet. Viverra mauris in aliquam sem. Pharetra convallis posuere morbi leo. Ut eu sem integer vitae justo. Odio ut enim blandit volutpat maecenas volutpat blandit. Ac tortor dignissim convallis aenean et. Commodo nulla facilisi nullam vehicula ipsum. Facilisi cras fermentum odio eu feugiat pretium nibh. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Quisque id diam vel quam elementum pulvinar etiam non. Pulvinar pellentesque habitant morbi tristique. Gravida quis blandit turpis cursus in hac habitasse. Id volutpat lacus laoreet non curabitur. Urna et pharetra pharetra massa massa ultricies. Volutpat maecenas volutpat blandit aliquam etiam. Pellentesque massa placerat duis ultricies lacus sed turpis. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Magna fermentum iaculis eu non diam.

In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Diam ut venenatis tellus in metus vulputate. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Hac habitasse platea dictumst vestibulum rhoncus est. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Erat pellentesque adipiscing commodo elit at. Venenatis cras sed felis eget velit. Ultrices neque ornare aenean euismod elementum. Nulla porttitor massa id neque. Netus et malesuada fames ac turpis egestas sed. Netus et malesuada fames ac turpis egestas integer eget. Sapien eget mi proin sed. Justo eget magna fermentum iaculis eu non diam. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam purus. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Leo integer malesuada nunc vel risus commodo viverra maecenas. Ac tortor vitae purus faucibus.

Odio ut sem nulla pharetra diam. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Iaculis eu non diam phasellus vestibulum lorem. Enim lobortis scelerisque fermentum dui. Amet aliquam id diam maecenas. Sed risus pretium quam vulputate dignissim suspendisse in est. Magna sit amet purus gravida quis blandit. Nulla pellentesque dignissim enim sit. Enim nunc faucibus a pellentesque sit. Nunc sed augue lacus viverra vitae congue eu. Enim nec dui nunc mattis enim ut tellus elementum. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Sed euismod nisi porta lorem mollis aliquam ut porttitor. Est velit egestas dui id ornare arcu odio. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Dolor magna eget est lorem. Gravida quis blandit turpis cursus in hac habitasse. Lectus proin nibh nisl condimentum. Morbi enim nunc faucibus a pellentesque sit amet.

At quis risus sed vulputate odio ut enim. Neque laoreet suspendisse interdum consectetur libero id faucibus. Euismod lacinia at quis risus. Volutpat ac tincidunt vitae semper quis lectus. Massa sapien faucibus et molestie ac feugiat sed. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Lacus sed turpis tincidunt id. Odio facilisis mauris sit amet massa vitae. Nulla aliquet porttitor lacus luctus accumsan tortor. Dui sapien eget mi proin sed libero enim. Arcu felis bibendum ut tristique et egestas quis ipsum. Vulputate ut pharetra sit amet aliquam. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Urna nunc id cursus metus aliquam. Diam quis enim lobortis scelerisque. Nullam non nisi est sit amet.

Sed id semper risus in. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Feugiat in fermentum posuere urna nec tincidunt. Pharetra massa massa ultricies mi quis hendrerit. Posuere morbi leo urna molestie at elementum eu. Enim neque volutpat ac tincidunt vitae. Adipiscing elit pellentesque habitant morbi tristique senectus. Est placerat in egestas erat imperdiet sed euismod nisi porta. Varius sit amet mattis vulputate. Eu ultrices vitae auctor eu augue ut. Id semper risus in hendrerit gravida rutrum quisque non tellus. Nibh nisl condimentum id venenatis. Aliquet bibendum enim facilisis gravida neque. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet.

Ultrices tincidunt arcu non sodales. Arcu dictum varius duis at consectetur lorem donec massa. Volutpat sed cras ornare arcu dui. Eget egestas purus viverra accumsan in. Eget felis eget nunc lobortis mattis aliquam faucibus purus. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Aliquet enim tortor at auctor urna nunc. Egestas quis ipsum suspendisse ultrices. Est pellentesque elit ullamcorper dignissim. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Quisque non tellus orci ac auctor augue mauris augue. Odio ut sem nulla pharetra diam sit amet. Consequat semper viverra nam libero. Placerat vestibulum lectus mauris ultrices eros. Velit ut tortor pretium viverra suspendisse potenti. Elit ut aliquam purus sit amet luctus venenatis lectus magna. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Cras ornare arcu dui vivamus arcu.

Dui nunc mattis enim ut tellus elementum sagittis vitae. Vehicula ipsum a arcu cursus vitae congue. Et odio pellentesque diam volutpat commodo sed egestas. Non consectetur a erat nam at lectus urna duis convallis. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Sit amet dictum sit amet justo. Aenean sed adipiscing diam donec adipiscing tristique risus nec. Felis eget nunc lobortis mattis aliquam faucibus purus in. Tellus pellentesque eu tincidunt tortor aliquam nulla. Id faucibus nisl tincidunt eget. Magna sit amet purus gravida. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Nisl tincidunt eget nullam non nisi est sit amet. Lectus sit amet est placerat in egestas erat imperdiet.

Ut ornare lectus sit amet est placerat. Tempus urna et pharetra pharetra massa. Mattis aliquam faucibus purus in massa tempor nec feugiat. Condimentum id venenatis a condimentum. Sed euismod nisi porta lorem mollis aliquam. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Sollicitudin ac orci phasellus egestas tellus rutrum. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Faucibus interdum posuere lorem ipsum. Non pulvinar neque laoreet suspendisse. Et odio pellentesque diam volutpat commodo sed.

Imperdiet nulla malesuada pellentesque elit eget gravida cum. Consequat nisl vel pretium lectus quam. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Felis eget velit aliquet sagittis id consectetur purus ut faucibus. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Tortor posuere ac ut consequat semper viverra nam libero. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Sit amet cursus sit amet dictum sit amet justo. Sed risus pretium quam vulputate. Suscipit adipiscing bibendum est ultricies integer quis auctor elit. Nunc sed velit dignissim sodales ut eu sem integer vitae. Posuere urna nec tincidunt praesent semper feugiat. Id consectetur purus ut faucibus pulvinar elementum integer enim. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam.

Etiam sit amet nisl purus in mollis. Tellus in hac habitasse platea dictumst vestibulum. Eu scelerisque felis imperdiet proin fermentum leo vel. Placerat vestibulum lectus mauris ultrices eros. Augue ut lectus arcu bibendum at varius. Bibendum arcu vitae elementum curabitur vitae. Velit aliquet sagittis id consectetur purus ut faucibus. Maecenas volutpat blandit aliquam etiam erat. Ut faucibus pulvinar elementum integer enim. Tortor dignissim convallis aenean et tortor at risus. Velit dignissim sodales ut eu sem integer. Nunc sed blandit libero volutpat sed cras ornare arcu. A lacus vestibulum sed arcu non. Justo donec enim diam vulputate ut. Tristique senectus et netus et malesuada fames ac turpis egestas.

Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Quis hendrerit dolor magna eget est lorem. Ut faucibus pulvinar elementum integer. Nunc sed velit dignissim sodales ut eu sem integer vitae. Velit euismod in pellentesque massa placerat duis ultricies. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Sit amet nulla facilisi morbi tempus iaculis urna. Nunc mattis enim ut tellus elementum sagittis. Ultricies tristique nulla aliquet enim tortor. Cras semper auctor neque vitae. Neque laoreet suspendisse interdum consectetur. Amet mauris commodo quis imperdiet massa.

Velit dignissim sodales ut eu sem. Sem et tortor consequat id porta nibh venenatis cras. Platea dictumst quisque sagittis purus sit amet. Pellentesque diam volutpat commodo sed egestas egestas. Ipsum suspendisse ultrices gravida dictum fusce. Nunc sed velit dignissim sodales ut eu sem. Aenean et tortor at risus viverra adipiscing at. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Vitae nunc sed velit dignissim sodales. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Sit amet massa vitae tortor condimentum lacinia. Adipiscing bibendum est ultricies integer. Elit eget gravida cum sociis natoque penatibus et magnis dis. Vitae tortor condimentum lacinia quis.

Enim facilisis gravida neque convallis a cras. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus sed. Neque ornare aenean euismod elementum nisi quis. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Diam maecenas ultricies mi eget mauris pharetra et. Porta lorem mollis aliquam ut porttitor leo a diam. Nec feugiat in fermentum posuere urna nec. Felis bibendum ut tristique et egestas quis. Magna ac placerat vestibulum lectus mauris ultrices eros. Lectus vestibulum mattis ullamcorper velit sed.

Odio ut enim blandit volutpat maecenas volutpat. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Cras semper auctor neque vitae tempus quam pellentesque. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Viverra adipiscing at in tellus. Mauris pharetra et ultrices neque ornare aenean euismod elementum. Tellus in metus vulputate eu. Suspendisse sed nisi lacus sed viverra tellus in. Scelerisque purus semper eget duis at tellus at urna. In nulla posuere sollicitudin aliquam ultrices sagittis.

Vitae tortor condimentum lacinia quis. Vulputate odio ut enim blandit volutpat maecenas. Amet mattis vulputate enim nulla aliquet porttitor. Velit laoreet id donec ultrices tincidunt arcu non sodales. Eget magna fermentum iaculis eu non diam phasellus vestibulum. Venenatis urna cursus eget nunc scelerisque. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Ut etiam sit amet nisl purus in. Amet commodo nulla facilisi nullam vehicula ipsum. Vitae sapien pellentesque habitant morbi tristique. Aliquet eget sit amet tellus cras adipiscing. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Amet mattis vulputate enim nulla aliquet. Eget egestas purus viverra accumsan in nisl. Aliquam sem et tortor consequat id porta nibh. Hendrerit gravida rutrum quisque non. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Interdum consectetur libero id faucibus. Tellus orci ac auctor augue mauris augue neque gravida. A diam sollicitudin tempor id eu nisl nunc mi.

At in tellus integer feugiat scelerisque varius morbi. Dolor morbi non arcu risus. Est sit amet facilisis magna etiam tempor orci. Sit amet est placerat in egestas erat imperdiet sed. Etiam erat velit scelerisque in dictum non consectetur. Aliquam ultrices sagittis orci a scelerisque. Euismod quis viverra nibh cras pulvinar mattis nunc sed. Orci porta non pulvinar neque laoreet. Arcu non sodales neque sodales ut etiam. Gravida quis blandit turpis cursus. Commodo ullamcorper a lacus vestibulum sed arcu non. Penatibus et magnis dis parturient montes.

Feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Varius quam quisque id diam vel quam elementum pulvinar. Scelerisque felis imperdiet proin fermentum leo vel orci. Ac turpis egestas maecenas pharetra convallis posuere. Sapien eget mi proin sed libero enim. Nisi vitae suscipit tellus mauris. Purus sit amet volutpat consequat mauris nunc. Non tellus orci ac auctor. Massa tincidunt dui ut ornare lectus sit amet est. Ultricies integer quis auctor elit sed vulputate mi. Sit amet venenatis urna cursus eget nunc. Ullamcorper a lacus vestibulum sed arcu non odio. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Viverra orci sagittis eu volutpat odio facilisis mauris sit amet. Risus ultricies tristique nulla aliquet enim. Mauris nunc congue nisi vitae.

Tincidunt eget nullam non nisi est sit amet facilisis magna. A arcu cursus vitae congue mauris rhoncus aenean. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Tellus molestie nunc non blandit massa enim nec dui. Nunc mattis enim ut tellus elementum. Integer vitae justo eget magna fermentum iaculis. Neque sodales ut etiam sit amet nisl purus in. Ac turpis egestas maecenas pharetra. Tortor consequat id porta nibh. Integer feugiat scelerisque varius morbi enim nunc faucibus. Nulla aliquet porttitor lacus luctus. Integer eget aliquet nibh praesent tristique. Ultricies mi quis hendrerit dolor magna eget. Quis lectus nulla at volutpat diam. Eu nisl nunc mi ipsum. Adipiscing commodo elit at imperdiet. Blandit massa enim nec dui nunc mattis. Vitae congue eu consequat ac felis. Eget aliquet nibh praesent tristique magna sit. Tempor orci dapibus ultrices in iaculis nunc.

Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Aliquet porttitor lacus luctus accumsan tortor posuere ac ut consequat. Mollis nunc sed id semper risus in hendrerit gravida. Posuere lorem ipsum dolor sit. Etiam tempor orci eu lobortis elementum nibh. Vulputate mi sit amet mauris commodo quis. Tortor id aliquet lectus proin nibh nisl condimentum id. Semper viverra nam libero justo laoreet sit amet. Nulla porttitor massa id neque aliquam vestibulum morbi. Orci ac auctor augue mauris augue neque gravida in fermentum. Eget est lorem ipsum dolor sit. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Posuere ac ut consequat semper viverra nam libero justo. Tempus quam pellentesque nec nam aliquam sem et tortor. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Praesent semper feugiat nibh sed pulvinar. Bibendum ut tristique et egestas. Quam id leo in vitae.

Eu augue ut lectus arcu bibendum. Est velit egestas dui id ornare arcu odio. Massa tincidunt nunc pulvinar sapien et. Arcu felis bibendum ut tristique et egestas quis ipsum. Et molestie ac feugiat sed lectus. Tristique senectus et netus et malesuada. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Facilisis volutpat est velit egestas dui id. Proin sagittis nisl rhoncus mattis. Amet nisl purus in mollis nunc sed id.

Cras ornare arcu dui vivamus arcu felis bibendum. Egestas sed sed risus pretium quam. Diam quam nulla porttitor massa. Eget egestas purus viverra accumsan in nisl nisi scelerisque. Non pulvinar neque laoreet suspendisse interdum consectetur. Elementum tempus egestas sed sed risus. Auctor neque vitae tempus quam. Diam phasellus vestibulum lorem sed. Convallis convallis tellus id interdum velit laoreet. Sit amet venenatis urna cursus eget nunc scelerisque viverra. Odio ut sem nulla pharetra diam. Donec ultrices tincidunt arcu non sodales neque sodales ut etiam. Fermentum dui faucibus in ornare quam viverra orci. Amet facilisis magna etiam tempor orci eu lobortis. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Duis ut diam quam nulla porttitor massa id neque. Vitae turpis massa sed elementum tempus egestas sed sed risus. Quisque egestas diam in arcu cursus euismod quis viverra. Sit amet massa vitae tortor condimentum lacinia quis vel.

Quam nulla porttitor massa id neque. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Quis auctor elit sed vulputate mi sit amet mauris commodo. Quisque sagittis purus sit amet volutpat. Velit sed ullamcorper morbi tincidunt ornare massa eget. Ipsum suspendisse ultrices gravida dictum fusce. Nisi porta lorem mollis aliquam ut porttitor leo a. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Integer vitae justo eget magna. Vitae proin sagittis nisl rhoncus mattis rhoncus. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Sed euismod nisi porta lorem mollis. Ac turpis egestas integer eget. Nisi lacus sed viverra tellus in hac habitasse. Egestas dui id ornare arcu odio ut sem. Nisi scelerisque eu ultrices vitae auctor eu augue.

Semper auctor neque vitae tempus quam pellentesque nec. Nec ullamcorper sit amet risus nullam eget felis. Libero enim sed faucibus turpis in eu mi. Risus viverra adipiscing at in tellus integer feugiat. Praesent tristique magna sit amet purus. Sed libero enim sed faucibus. Imperdiet proin fermentum leo vel orci porta. Eget velit aliquet sagittis id. Pellentesque id nibh tortor id aliquet lectus proin nibh. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Sit amet nisl suscipit adipiscing bibendum est. Ultricies lacus sed turpis tincidunt id aliquet. Vel turpis nunc eget lorem dolor sed viverra ipsum nunc.

Lorem donec massa sapien faucibus et. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Commodo ullamcorper a lacus vestibulum sed arcu. Rhoncus mattis rhoncus urna neque viverra. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Est lorem ipsum dolor sit. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Eget nulla facilisi etiam dignissim diam. Massa ultricies mi quis hendrerit dolor. Augue lacus viverra vitae congue eu. Lectus arcu bibendum at varius vel pharetra vel turpis nunc. Amet purus gravida quis blandit turpis. Venenatis cras sed felis eget velit aliquet. Ultrices neque ornare aenean euismod elementum nisi quis. Sodales ut eu sem integer. Rhoncus dolor purus non enim praesent elementum facilisis. Est ultricies integer quis auctor elit sed vulputate mi sit. In nisl nisi scelerisque eu ultrices vitae. Ac felis donec et odio pellentesque. Enim neque volutpat ac tincidunt vitae.

Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Ultrices sagittis orci a scelerisque. Ante metus dictum at tempor commodo ullamcorper a lacus. In fermentum et sollicitudin ac. Adipiscing vitae proin sagittis nisl. Proin libero nunc consequat interdum varius sit. Phasellus egestas tellus rutrum tellus pellentesque eu. Arcu dictum varius duis at consectetur lorem donec. Quam lacus suspendisse faucibus interdum. Sodales neque sodales ut etiam sit. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Faucibus pulvinar elementum integer enim neque. Eu feugiat pretium nibh ipsum consequat nisl vel. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Nisl condimentum id venenatis a condimentum. Netus et malesuada fames ac. Venenatis a condimentum vitae sapien pellentesque. Cursus sit amet dictum sit. Nunc faucibus a pellentesque sit amet.

Volutpat sed cras ornare arcu. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Nibh ipsum consequat nisl vel. Sed id semper risus in hendrerit. Dictum non consectetur a erat nam at lectus. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Pellentesque adipiscing commodo elit at imperdiet. Sagittis vitae et leo duis ut diam. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. At augue eget arcu dictum varius duis at consectetur lorem. Turpis egestas maecenas pharetra convallis posuere morbi leo. Augue ut lectus arcu bibendum at varius vel pharetra. Commodo nulla facilisi nullam vehicula ipsum a arcu. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Condimentum id venenatis a condimentum. Vitae turpis massa sed elementum tempus. Blandit turpis cursus in hac habitasse platea dictumst quisque.

Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Felis bibendum ut tristique et egestas quis. Felis eget nunc lobortis mattis aliquam faucibus purus in. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Urna duis convallis convallis tellus id interdum velit laoreet. Egestas tellus rutrum tellus pellentesque eu. Tortor pretium viverra suspendisse potenti nullam ac tortor. Eu sem integer vitae justo eget magna fermentum iaculis eu. Habitant morbi tristique senectus et netus. Nisl tincidunt eget nullam non nisi est sit. Porttitor eget dolor morbi non arcu risus quis. Orci sagittis eu volutpat odio facilisis. Pharetra pharetra massa massa ultricies mi quis. Viverra accumsan in nisl nisi scelerisque. Dui sapien eget mi proin. Id diam maecenas ultricies mi eget mauris pharetra.

Non diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Lobortis feugiat vivamus at augue eget arcu dictum varius duis. Eu nisl nunc mi ipsum. Iaculis nunc sed augue lacus viverra vitae. Suspendisse sed nisi lacus sed viverra tellus in hac habitasse. Faucibus purus in massa tempor nec feugiat nisl pretium. Facilisis volutpat est velit egestas dui id ornare arcu odio. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Vitae turpis massa sed elementum tempus egestas. Dictum at tempor commodo ullamcorper. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Ullamcorper velit sed ullamcorper morbi tincidunt. Elit eget gravida cum sociis natoque penatibus et magnis. Nunc sed velit dignissim sodales ut eu sem. Enim diam vulputate ut pharetra sit amet aliquam id diam. Elit pellentesque habitant morbi tristique senectus et netus et malesuada. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Sapien nec sagittis aliquam malesuada bibendum arcu vitae.

Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Lobortis scelerisque fermentum dui faucibus in ornare. Tellus mauris a diam maecenas sed enim ut. Tortor dignissim convallis aenean et. Lacinia quis vel eros donec ac odio tempor orci. Scelerisque in dictum non consectetur a erat nam. Non diam phasellus vestibulum lorem sed risus ultricies tristique. Facilisis leo vel fringilla est ullamcorper eget nulla. At quis risus sed vulputate odio. Ridiculus mus mauris vitae ultricies leo. Arcu cursus euismod quis viverra nibh cras. Tellus orci ac auctor augue mauris augue. Urna et pharetra pharetra massa massa.

Aliquet lectus proin nibh nisl. Orci sagittis eu volutpat odio facilisis mauris sit amet. Gravida rutrum quisque non tellus. Ut eu sem integer vitae. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Fames ac turpis egestas integer eget aliquet. Aliquam ultrices sagittis orci a scelerisque purus semper. Posuere urna nec tincidunt praesent semper feugiat nibh sed pulvinar. Id velit ut tortor pretium viverra suspendisse. Enim neque volutpat ac tincidunt. Duis at tellus at urna condimentum mattis pellentesque. Auctor augue mauris augue neque gravida in fermentum. Nisl suscipit adipiscing bibendum est. Ut eu sem integer vitae justo eget magna.

Tincidunt nunc pulvinar sapien et ligula. Sed vulputate odio ut enim blandit volutpat maecenas. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Dictum fusce ut placerat orci. Enim nunc faucibus a pellentesque sit amet. Nisi est sit amet facilisis magna etiam tempor orci eu. Semper risus in hendrerit gravida rutrum. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Nisi porta lorem mollis aliquam ut. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Congue quisque egestas diam in arcu. Suspendisse ultrices gravida dictum fusce ut. Viverra justo nec ultrices dui sapien eget. Amet justo donec enim diam. Felis bibendum ut tristique et. Senectus et netus et malesuada fames ac turpis.

Libero enim sed faucibus turpis in. Varius quam quisque id diam vel quam elementum. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Hendrerit dolor magna eget est lorem. Tortor condimentum lacinia quis vel eros donec ac odio. Rhoncus urna neque viverra justo nec ultrices dui. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Aliquam purus sit amet luctus venenatis lectus. Arcu felis bibendum ut tristique et egestas quis ipsum. Ut pharetra sit amet aliquam id diam. Urna cursus eget nunc scelerisque viverra mauris in.

Nam aliquam sem et tortor consequat id porta nibh venenatis. Non sodales neque sodales ut. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Non arcu risus quis varius. Pretium fusce id velit ut tortor pretium. Viverra ipsum nunc aliquet bibendum enim facilisis. Integer eget aliquet nibh praesent tristique magna. Mauris cursus mattis molestie a iaculis at erat. Tristique senectus et netus et malesuada fames ac turpis. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Lacinia quis vel eros donec ac odio tempor. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Vestibulum lorem sed risus ultricies tristique nulla. Faucibus interdum posuere lorem ipsum. Mattis aliquam faucibus purus in massa tempor. Semper feugiat nibh sed pulvinar proin. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. At risus viverra adipiscing at in.

Felis bibendum ut tristique et. Ut tellus elementum sagittis vitae et. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Dignissim sodales ut eu sem integer vitae justo. Platea dictumst quisque sagittis purus sit amet volutpat. Fermentum leo vel orci porta non pulvinar neque. Tortor id aliquet lectus proin nibh. Dignissim suspendisse in est ante in nibh. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Laoreet non curabitur gravida arcu ac tortor dignissim convallis. Interdum varius sit amet mattis vulputate enim nulla aliquet. Odio morbi quis commodo odio aenean sed. Ac odio tempor orci dapibus. Donec enim diam vulputate ut pharetra. Ipsum consequat nisl vel pretium lectus. Sed augue lacus viverra vitae congue eu. Diam vel quam elementum pulvinar etiam non quam lacus. Et malesuada fames ac turpis egestas. Mi quis hendrerit dolor magna eget.

Ut ornare lectus sit amet est. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Viverra adipiscing at in tellus integer feugiat scelerisque. Arcu non odio euismod lacinia at quis risus. Et tortor consequat id porta nibh. Tempor nec feugiat nisl pretium. Scelerisque viverra mauris in aliquam sem fringilla ut. Turpis egestas maecenas pharetra convallis. Consequat mauris nunc congue nisi vitae suscipit tellus. Tempus imperdiet nulla malesuada pellentesque. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Porttitor leo a diam sollicitudin tempor id eu. Ac tortor vitae purus faucibus ornare suspendisse. Urna id volutpat lacus laoreet. Cursus vitae congue mauris rhoncus aenean vel elit. Nulla facilisi morbi tempus iaculis urna id volutpat lacus laoreet.

Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Volutpat ac tincidunt vitae semper quis lectus. Nibh sed pulvinar proin gravida hendrerit lectus a. Cursus turpis massa tincidunt dui ut ornare lectus. Cras tincidunt lobortis feugiat vivamus. Viverra orci sagittis eu volutpat odio. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus nisl. In hac habitasse platea dictumst. A cras semper auctor neque vitae tempus. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Massa enim nec dui nunc mattis enim ut tellus. Donec ultrices tincidunt arcu non sodales. Nunc pulvinar sapien et ligula ullamcorper malesuada proin. Eu non diam phasellus vestibulum lorem sed risus.

Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nec feugiat nisl pretium fusce id. Sit amet consectetur adipiscing elit ut aliquam. Ornare arcu odio ut sem nulla pharetra diam sit amet. Nunc non blandit massa enim nec dui nunc. Integer enim neque volutpat ac tincidunt. Sodales neque sodales ut etiam. Elementum eu facilisis sed odio morbi quis commodo odio aenean. Malesuada bibendum arcu vitae elementum curabitur vitae nunc. Interdum varius sit amet mattis vulputate enim nulla. Amet consectetur adipiscing elit ut. Volutpat blandit aliquam etiam erat velit scelerisque in.

Tempus urna et pharetra pharetra massa massa ultricies. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Id semper risus in hendrerit. Suspendisse interdum consectetur libero id. Proin nibh nisl condimentum id venenatis a condimentum. Porta lorem mollis aliquam ut. Velit laoreet id donec ultrices tincidunt. Quis varius quam quisque id diam. Sapien eget mi proin sed libero enim sed faucibus. Quis viverra nibh cras pulvinar mattis nunc sed. Integer eget aliquet nibh praesent tristique magna sit. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Euismod nisi porta lorem mollis. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. A diam maecenas sed enim ut sem. Id faucibus nisl tincidunt eget nullam non nisi est sit. Sed odio morbi quis commodo odio aenean sed. Amet nulla facilisi morbi tempus. Ut faucibus pulvinar elementum integer.

Turpis cursus in hac habitasse. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Duis ultricies lacus sed turpis tincidunt id. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Enim blandit volutpat maecenas volutpat blandit aliquam etiam. Nulla at volutpat diam ut. Lacus vestibulum sed arcu non odio. Gravida cum sociis natoque penatibus et magnis dis parturient. Nulla malesuada pellentesque elit eget gravida cum. Commodo ullamcorper a lacus vestibulum sed arcu non odio. Ullamcorper morbi tincidunt ornare massa eget egestas. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Integer eget aliquet nibh praesent tristique magna. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Et ligula ullamcorper malesuada proin libero nunc consequat. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan.

Nisi porta lorem mollis aliquam. Facilisis sed odio morbi quis commodo odio aenean. Eu sem integer vitae justo eget. Gravida neque convallis a cras semper auctor neque vitae. Nulla facilisi cras fermentum odio eu feugiat. Libero enim sed faucibus turpis in eu mi bibendum neque. Id aliquet lectus proin nibh. Odio eu feugiat pretium nibh ipsum. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Interdum velit euismod in pellentesque massa placerat duis ultricies. Justo eget magna fermentum iaculis eu non. Viverra vitae congue eu consequat ac felis. Dictum fusce ut placerat orci. Vel fringilla est ullamcorper eget nulla facilisi etiam. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Augue ut lectus arcu bibendum. Congue nisi vitae suscipit tellus mauris a diam.

Nunc consequat interdum varius sit amet mattis vulputate. Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Eu mi bibendum neque egestas congue quisque egestas diam. Orci phasellus egestas tellus rutrum. Nisi vitae suscipit tellus mauris a diam maecenas. Leo in vitae turpis massa. Diam quis enim lobortis scelerisque. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Nibh cras pulvinar mattis nunc sed. Varius vel pharetra vel turpis nunc.

Aliquam ultrices sagittis orci a scelerisque purus semper. Nunc eget lorem dolor sed viverra. Erat velit scelerisque in dictum non consectetur a erat nam. Ac felis donec et odio pellentesque diam volutpat commodo sed. Lacus vel facilisis volutpat est velit egestas. Lorem donec massa sapien faucibus et molestie ac feugiat sed. Id neque aliquam vestibulum morbi blandit cursus. Suspendisse potenti nullam ac tortor vitae purus. Consequat nisl vel pretium lectus quam id. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Malesuada pellentesque elit eget gravida cum. Urna nunc id cursus metus aliquam eleifend mi in nulla.

Justo laoreet sit amet cursus sit amet. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Justo donec enim diam vulputate ut pharetra sit amet. Viverra adipiscing at in tellus integer feugiat scelerisque varius. Fermentum leo vel orci porta non pulvinar neque. Viverra suspendisse potenti nullam ac tortor. Blandit libero volutpat sed cras ornare. Nulla porttitor massa id neque. Euismod nisi porta lorem mollis aliquam ut. In iaculis nunc sed augue lacus viverra vitae congue. Volutpat diam ut venenatis tellus. Ullamcorper a lacus vestibulum sed. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Eu tincidunt tortor aliquam nulla facilisi. Facilisis gravida neque convallis a cras semper. Dignissim diam quis enim lobortis scelerisque fermentum.

Ut sem viverra aliquet eget sit. Et ultrices neque ornare aenean. Lobortis elementum nibh tellus molestie nunc non. Nibh mauris cursus mattis molestie a iaculis at erat. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Ultrices vitae auctor eu augue ut. Arcu non sodales neque sodales ut etiam sit. Lectus quam id leo in vitae. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Morbi blandit cursus risus at ultrices mi. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Sodales ut etiam sit amet nisl purus in mollis.

Risus ultricies tristique nulla aliquet enim. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Nisi porta lorem mollis aliquam ut porttitor leo a. Imperdiet sed euismod nisi porta. Semper eget duis at tellus at urna condimentum mattis. Libero nunc consequat interdum varius sit amet mattis vulputate enim. Nunc id cursus metus aliquam eleifend mi in nulla. Nisi lacus sed viverra tellus in hac habitasse platea dictumst. Vitae suscipit tellus mauris a diam maecenas sed enim. Pharetra convallis posuere morbi leo urna molestie. Dui vivamus arcu felis bibendum. Sem fringilla ut morbi tincidunt augue interdum. Vel orci porta non pulvinar. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Volutpat est velit egestas dui id. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Proin sagittis nisl rhoncus mattis rhoncus urna neque.

Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Eu feugiat pretium nibh ipsum consequat nisl. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Quam id leo in vitae turpis. Leo duis ut diam quam nulla porttitor massa. Eget dolor morbi non arcu risus quis. Elementum pulvinar etiam non quam lacus suspendisse. Est velit egestas dui id ornare arcu odio. Libero enim sed faucibus turpis in eu mi bibendum. Sit amet consectetur adipiscing elit ut aliquam purus sit. Mi sit amet mauris commodo. Aliquam ut porttitor leo a diam sollicitudin tempor id eu. At consectetur lorem donec massa sapien faucibus. Amet nisl purus in mollis nunc. Tincidunt nunc pulvinar sapien et ligula. Libero id faucibus nisl tincidunt eget nullam non nisi. Cras semper auctor neque vitae tempus quam pellentesque nec. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Est pellentesque elit ullamcorper dignissim cras. Mi bibendum neque egestas congue quisque egestas diam in.

Tempor nec feugiat nisl pretium fusce id velit. Vitae tempus quam pellentesque nec nam aliquam. Eget nunc scelerisque viverra mauris. In iaculis nunc sed augue lacus viverra. Morbi tristique senectus et netus et malesuada. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Nibh venenatis cras sed felis eget velit aliquet. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Gravida neque convallis a cras. Justo nec ultrices dui sapien eget mi proin. Faucibus vitae aliquet nec ullamcorper sit amet. Tincidunt id aliquet risus feugiat in ante metus dictum. Quis varius quam quisque id diam vel. Amet aliquam id diam maecenas ultricies. Sed enim ut sem viverra aliquet eget sit. Tincidunt tortor aliquam nulla facilisi cras fermentum. Ultricies lacus sed turpis tincidunt. Sagittis nisl rhoncus mattis rhoncus urna.

At in tellus integer feugiat. Sociis natoque penatibus et magnis dis parturient montes nascetur. Condimentum lacinia quis vel eros donec. Ipsum nunc aliquet bibendum enim facilisis gravida. Amet aliquam id diam maecenas ultricies mi eget mauris pharetra. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac ut. Nulla facilisi morbi tempus iaculis urna id. At varius vel pharetra vel turpis nunc. Senectus et netus et malesuada fames ac. Neque vitae tempus quam pellentesque nec nam aliquam sem et. Netus et malesuada fames ac turpis egestas. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor.

Fames ac turpis egestas sed tempus urna. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Pharetra diam sit amet nisl suscipit adipiscing. A pellentesque sit amet porttitor eget dolor morbi non arcu. Amet consectetur adipiscing elit duis tristique. Et malesuada fames ac turpis egestas sed. Nunc non blandit massa enim. Integer malesuada nunc vel risus commodo viverra maecenas. Tellus at urna condimentum mattis pellentesque. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Vehicula ipsum a arcu cursus. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. In nibh mauris cursus mattis. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. In aliquam sem fringilla ut morbi tincidunt. Donec enim diam vulputate ut pharetra sit amet. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Elementum integer enim neque volutpat ac tincidunt vitae semper.

Sed id semper risus in. Fringilla ut morbi tincidunt augue. Mollis aliquam ut porttitor leo. Pharetra sit amet aliquam id diam maecenas ultricies. Libero justo laoreet sit amet cursus sit amet dictum sit. Massa id neque aliquam vestibulum morbi blandit cursus risus. Sapien pellentesque habitant morbi tristique senectus. Metus dictum at tempor commodo ullamcorper. Bibendum est ultricies integer quis auctor elit sed. Dolor magna eget est lorem ipsum dolor. Natoque penatibus et magnis dis. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Morbi tristique senectus et netus et.

Cursus in hac habitasse platea dictumst. Enim blandit volutpat maecenas volutpat. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Semper eget duis at tellus at urna condimentum mattis pellentesque. Sed nisi lacus sed viverra tellus. Vel turpis nunc eget lorem dolor sed. Dapibus ultrices in iaculis nunc. In nulla posuere sollicitudin aliquam ultrices sagittis orci a. Ullamcorper a lacus vestibulum sed arcu non odio. Sodales ut etiam sit amet nisl purus. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Faucibus a pellentesque sit amet porttitor eget dolor. Vel quam elementum pulvinar etiam non quam. Nunc sed id semper risus in hendrerit gravida rutrum. Adipiscing diam donec adipiscing tristique risus. Dolor purus non enim praesent. Id ornare arcu odio ut sem nulla.

Vivamus arcu felis bibendum ut tristique et egestas quis. Sed egestas egestas fringilla phasellus faucibus scelerisque. Ut eu sem integer vitae justo eget. Velit aliquet sagittis id consectetur purus ut faucibus. Integer vitae justo eget magna fermentum. Volutpat ac tincidunt vitae semper quis. Enim neque volutpat ac tincidunt. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. A cras semper auctor neque vitae. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Morbi tempus iaculis urna id.

Lectus arcu bibendum at varius vel pharetra vel. Ipsum dolor sit amet consectetur adipiscing. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Tristique senectus et netus et malesuada fames. Consectetur lorem donec massa sapien. Habitant morbi tristique senectus et netus et malesuada. Ornare suspendisse sed nisi lacus sed viverra. Fringilla urna porttitor rhoncus dolor. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim. Facilisis magna etiam tempor orci eu. At tempor commodo ullamcorper a lacus vestibulum sed.

Dui ut ornare lectus sit amet est placerat. Facilisis gravida neque convallis a. Pellentesque adipiscing commodo elit at imperdiet. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Urna id volutpat lacus laoreet. Feugiat vivamus at augue eget arcu. Et netus et malesuada fames ac turpis egestas sed tempus. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Viverra suspendisse potenti nullam ac tortor vitae.

Adipiscing elit duis tristique sollicitudin nibh. Sem integer vitae justo eget magna fermentum iaculis. Massa placerat duis ultricies lacus sed turpis tincidunt id. Quis auctor elit sed vulputate mi sit amet mauris. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Velit egestas dui id ornare arcu odio ut sem nulla. Sit amet cursus sit amet. Mattis rhoncus urna neque viverra justo nec ultrices dui. Massa enim nec dui nunc mattis enim.

Commodo elit at imperdiet dui. Quis ipsum suspendisse ultrices gravida dictum fusce ut. Porta nibh venenatis cras sed felis eget velit aliquet. Diam sit amet nisl suscipit. Dui sapien eget mi proin sed. Interdum velit laoreet id donec ultrices tincidunt arcu non. Congue nisi vitae suscipit tellus mauris a diam maecenas. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Nam libero justo laoreet sit amet cursus sit amet. Pulvinar neque laoreet suspendisse interdum. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Ligula ullamcorper malesuada proin libero. Amet massa vitae tortor condimentum lacinia. Quis lectus nulla at volutpat diam ut venenatis tellus in.

Tempus iaculis urna id volutpat lacus. Dui ut ornare lectus sit amet est. Mattis rhoncus urna neque viverra justo nec ultrices dui. Odio pellentesque diam volutpat commodo sed egestas. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Felis imperdiet proin fermentum leo. Egestas sed tempus urna et pharetra. Pellentesque nec nam aliquam sem et tortor. Id aliquet risus feugiat in. Tortor aliquam nulla facilisi cras fermentum. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi etiam. Pellentesque diam volutpat commodo sed egestas egestas fringilla. Varius quam quisque id diam vel. Cras fermentum odio eu feugiat pretium nibh. Enim nec dui nunc mattis enim ut tellus elementum. Natoque penatibus et magnis dis. Aliquet eget sit amet tellus cras adipiscing enim eu turpis.

Eget egestas purus viverra accumsan in nisl nisi scelerisque. Magna ac placerat vestibulum lectus mauris ultrices eros in cursus. Consequat interdum varius sit amet. Quam nulla porttitor massa id neque aliquam vestibulum. Nec nam aliquam sem et tortor consequat id. Nulla aliquet porttitor lacus luctus accumsan. Ultricies mi quis hendrerit dolor magna eget est lorem. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Morbi tincidunt ornare massa eget egestas purus viverra accumsan. Dolor purus non enim praesent elementum. A diam sollicitudin tempor id eu nisl nunc mi ipsum.

Odio euismod lacinia at quis risus sed vulputate odio ut. Sem nulla pharetra diam sit amet nisl suscipit. Bibendum neque egestas congue quisque egestas diam in arcu cursus. Tellus mauris a diam maecenas sed enim ut sem. Tortor vitae purus faucibus ornare suspendisse sed. Vulputate eu scelerisque felis imperdiet proin fermentum leo. Suspendisse in est ante in nibh mauris cursus mattis molestie. Tempus egestas sed sed risus pretium quam vulputate dignissim suspendisse. Elit pellentesque habitant morbi tristique senectus. Aliquam vestibulum morbi blandit cursus risus. Lorem ipsum dolor sit amet consectetur adipiscing elit. Id nibh tortor id aliquet lectus proin nibh nisl. Bibendum enim facilisis gravida neque convallis a cras. Molestie at elementum eu facilisis sed odio morbi quis. Sit amet aliquam id diam maecenas ultricies. Sit amet dictum sit amet justo donec. Massa massa ultricies mi quis hendrerit dolor. Et odio pellentesque diam volutpat commodo sed egestas. Sed blandit libero volutpat sed cras ornare arcu dui. Sit amet consectetur adipiscing elit ut aliquam purus sit amet.

Augue eget arcu dictum varius. Facilisi cras fermentum odio eu feugiat. Tellus integer feugiat scelerisque varius. Nunc aliquet bibendum enim facilisis gravida neque convallis a. In pellentesque massa placerat duis. Risus in hendrerit gravida rutrum quisque non. Ut pharetra sit amet aliquam. Tristique magna sit amet purus gravida. Id donec ultrices tincidunt arcu non sodales neque. Sagittis eu volutpat odio facilisis mauris sit amet. Et netus et malesuada fames ac. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Luctus accumsan tortor posuere ac ut consequat semper. Tempus urna et pharetra pharetra massa. Justo nec ultrices dui sapien eget mi proin sed libero. Maecenas volutpat blandit aliquam etiam erat velit scelerisque.

Tortor consequat id porta nibh venenatis. Adipiscing enim eu turpis egestas pretium. Lorem ipsum dolor sit amet consectetur adipiscing elit. Leo a diam sollicitudin tempor id eu nisl. Ultricies tristique nulla aliquet enim tortor. Nec sagittis aliquam malesuada bibendum. Dis parturient montes nascetur ridiculus mus mauris vitae. Nunc sed augue lacus viverra vitae congue eu. Sodales ut eu sem integer vitae justo. Vestibulum sed arcu non odio euismod lacinia at quis risus. Vel turpis nunc eget lorem dolor sed viverra ipsum. Vestibulum sed arcu non odio euismod lacinia. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra.

Egestas sed tempus urna et. Sit amet aliquam id diam maecenas ultricies mi. Justo donec enim diam vulputate ut pharetra. Tincidunt ornare massa eget egestas purus viverra accumsan. Condimentum lacinia quis vel eros donec ac. Morbi tristique senectus et netus et malesuada fames. Libero enim sed faucibus turpis. Id diam vel quam elementum pulvinar. Non blandit massa enim nec dui nunc mattis enim ut. Nisl rhoncus mattis rhoncus urna neque viverra justo.

Sed vulputate mi sit amet mauris commodo quis. Diam quam nulla porttitor massa id neque. Nulla porttitor massa id neque aliquam vestibulum. Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Arcu non odio euismod lacinia at. Tellus molestie nunc non blandit massa enim nec. Magnis dis parturient montes nascetur. Scelerisque in dictum non consectetur a. Dui ut ornare lectus sit amet est. Sed adipiscing diam donec adipiscing tristique risus. Egestas congue quisque egestas diam in arcu cursus euismod quis.

Tempor id eu nisl nunc mi ipsum faucibus vitae. Molestie at elementum eu facilisis sed odio. Eu consequat ac felis donec et. Ut venenatis tellus in metus vulputate eu. Habitant morbi tristique senectus et netus et malesuada fames. Ultrices dui sapien eget mi. At tellus at urna condimentum mattis. Scelerisque in dictum non consectetur a erat nam at lectus. Aliquet nec ullamcorper sit amet risus nullam eget felis. Dui sapien eget mi proin sed libero enim sed faucibus. Sit amet nulla facilisi morbi.

Amet nulla facilisi morbi tempus iaculis urna id volutpat. Suscipit adipiscing bibendum est ultricies integer. Nam libero justo laoreet sit amet cursus. Nisl nunc mi ipsum faucibus vitae. Netus et malesuada fames ac turpis. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Fringilla urna porttitor rhoncus dolor purus. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Habitant morbi tristique senectus et netus. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Non odio euismod lacinia at quis risus sed. Pellentesque sit amet porttitor eget. In ante metus dictum at. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Fermentum leo vel orci porta non pulvinar neque. Tortor consequat id porta nibh venenatis cras sed felis eget. Id semper risus in hendrerit. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat.

Ac felis donec et odio pellentesque diam volutpat. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Purus non enim praesent elementum. Volutpat odio facilisis mauris sit amet. Nunc scelerisque viverra mauris in aliquam sem. At elementum eu facilisis sed odio morbi quis. Sed libero enim sed faucibus turpis in eu mi. Nunc scelerisque viverra mauris in aliquam sem. Nisl condimentum id venenatis a condimentum vitae. Viverra orci sagittis eu volutpat. Elementum nibh tellus molestie nunc non blandit. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Facilisi nullam vehicula ipsum a arcu. Pharetra convallis posuere morbi leo urna molestie.

Consequat id porta nibh venenatis cras sed felis. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Proin nibh nisl condimentum id. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Massa placerat duis ultricies lacus. Integer eget aliquet nibh praesent tristique magna sit. Tortor dignissim convallis aenean et tortor at risus viverra adipiscing. Mattis nunc sed blandit libero volutpat sed. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Porttitor lacus luctus accumsan tortor posuere ac. Ac turpis egestas sed tempus urna. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula ipsum.

In hendrerit gravida rutrum quisque non. Amet justo donec enim diam. Quis commodo odio aenean sed. Id cursus metus aliquam eleifend mi in nulla. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Etiam sit amet nisl purus in mollis. Varius vel pharetra vel turpis. Morbi leo urna molestie at elementum. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Platea dictumst vestibulum rhoncus est pellentesque elit. Quam quisque id diam vel quam elementum.

Dolor sit amet consectetur adipiscing. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Dignissim convallis aenean et tortor at risus viverra. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Volutpat lacus laoreet non curabitur gravida arcu. Non odio euismod lacinia at quis risus sed vulputate. Duis at consectetur lorem donec massa. Auctor elit sed vulputate mi sit amet mauris commodo quis. Amet consectetur adipiscing elit ut. Laoreet sit amet cursus sit. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Mollis aliquam ut porttitor leo a diam. Tincidunt augue interdum velit euismod in pellentesque massa placerat. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Ut faucibus pulvinar elementum integer enim. Dolor sit amet consectetur adipiscing elit. Gravida quis blandit turpis cursus. Faucibus pulvinar elementum integer enim neque volutpat.

Non diam phasellus vestibulum lorem sed risus ultricies tristique. Vitae congue eu consequat ac felis. Nulla at volutpat diam ut venenatis tellus in metus. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Magnis dis parturient montes nascetur. In ante metus dictum at tempor commodo ullamcorper a. Non pulvinar neque laoreet suspendisse interdum. Lorem ipsum dolor sit amet consectetur. Augue mauris augue neque gravida. Arcu non odio euismod lacinia at. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Mauris in aliquam sem fringilla ut morbi tincidunt. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Dictum non consectetur a erat nam at lectus. Augue ut lectus arcu bibendum at varius vel pharetra vel. Justo nec ultrices dui sapien eget. Risus sed vulputate odio ut enim blandit.
 */

#[tokio::main]
async fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() != 2 {
        println!("Usage: {} <seconds between checks>", args[0]);
        process::exit(1);
    }

    let seconds: u64 = match args[1].parse() {
        Ok(num) => num,
        Err(_) => {
            println!("Error: second argument must be a valid integer");
            process::exit(1);
        }
    };

    loop {
        let active_watchers = requests::get_active_watchers().await.unwrap();
        for watcher in active_watchers {
            if !Path::new(&watcher.path).exists() {
                requests::make_watcher_inactive(&watcher.name)
                    .await
                    .unwrap();
                continue;
            }

            let working_periods = requests::get_working_periods(watcher.id.unwrap())
                .await
                .unwrap();

            if working_periods.is_empty() {
                requests::new_working_periods(&watcher.name).await.unwrap();
                continue;
            }

            let last_update = &working_periods.last().unwrap().date;
            if is_older(Path::new(&watcher.path), last_update) {
                requests::new_working_periods(&watcher.name).await.unwrap();
            }
        }

        thread::sleep(Duration::from_secs(seconds));
    }
}

fn is_older(path: &Path, previous_modification: &str) -> bool {
    // Parse the previous modification string into a DateTime object
    let previous_modification_datetime: DateTime<Local> = Local
        .datetime_from_str(previous_modification, "%Y-%m-%dT%H:%M:%S%.f%z")
        .unwrap();

    // Recursively iterate over all the files and directories in the given path
    for entry in WalkDir::new(path).into_iter().filter_map(|e| e.ok()) {
        let entry_path = entry.path();

        // Get the metadata for the current file or directory
        let metadata = match fs::metadata(entry_path) {
            Ok(metadata) => metadata,
            Err(_) => continue, // Skip this entry if the metadata is not available
        };

        // Get the last modification time of the current file or directory as a DateTime object
        let last_modification_datetime = match metadata.modified() {
            Ok(system_time) => Local.timestamp_millis(
                system_time
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_millis() as i64,
            ),
            Err(_) => continue, // Skip this entry if the last modification time is not available
        };

        // Return true if the last modification time of the current file or directory is greater than the previous modification time
        if last_modification_datetime > previous_modification_datetime {
            return true;
        }
    }

    // Return false if no nested files or directories have a modification time greater than the previous modification time
    false
}
