[package]
name = "watch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rusqlite = "0.28.0"
lazy_static = "1.4.0"
serde = "1.0.151"